### ISSUE TITLE
Current isprime() is not correct

### ISSUE THREAD

**Issue by pettarin** [AVGP/js-parallelism-demos#1]
I appreciate that the main goal of the post is about the use of buffers to share data among threads (thank you for that), yet I think you might want to make the actual worker computation correct, for, if nothing else, avoiding confusion in the reader.

Your current code is such that: ``isprime(4)`` returns ``true``.

Probably you want ``<=`` instead of ``<`` (or no ``floor()`` call), in https://github.com/AVGP/js-parallelism-demos/blob/master/simple-worker/prime-worker.js#L17

Also, I think that your main loop https://github.com/AVGP/js-parallelism-demos/blob/master/simple-worker/prime-worker.js#L4 is somewhat harder than it should. For example, it tests even numbers, while you can deal with ``2`` as a special case, and loop over odd numbers only.

The same observations apply to the other workers.

**Comment by AVGP** [comment]
First things first: Thanks for pointing it out!

You're right that I didn't scrutinize over the code being correct as it's a mere illustration of long-running work in JavaScript and the available options to get things off the main thread.

Regarding easing it up by skipping even numbers - to be frank, the algorithm is terrible anyway, so I feel optimisations aren't necessary here. The goal of the code is to *inefficiently* do things to put stress on the device to begin with. If you'd want a good solution, you should probably use something like the [Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes) in the first place. The fact that the algorithm is bad is even mentioned in the post:

> Here we will use a very naive algorithm (there are much better ones available)

I'll see if I get around to fix the code & the excerpts in the code as well, unless you'd like to send a pull request instead, in which case I'll happily merge the corrections and credit you in the blog post.

I'll credit you anyway, though...

**Comment by AVGP** [comment]
Nevermind, I quickly fixed the code and will now update the post as well. Thanks again :)

**Comment by pettarin** [comment]
You are welcome. Thank you for your post, it was very informative for someone like me who is not a JS dev.
