### ISSUE TITLE
Error: Transferring workers has error

### ISSUE THREAD

**Issue by dynamite-bud** [AVGP/js-parallelism-demos#2]
When we transfer the buffer in postmessage. We are not able to access the buffer in the line 13 because buffer has a bytelength of 0 after being transferred to a worker.

![image](https://user-images.githubusercontent.com/41326026/167395249-46e9ab3e-c992-44dd-98de-a5df8161891e.png)

**Comment by AVGP** [comment]
Indeed, good catch.

There were two issues at play here:

1) A typo - of course we can't reference a transferred buffer. It should've been `msg.data.buffer` as you posted.
2) It used to be fine to reuse an ArrayView by using `.set` but doesn't seem to be fine anymore. So a new one needs to be created.

Pushed a fix, thanks.
